Лабораторная работа номер 1

In [ ]:
Упражнение 1

In [1]:
2*3

6

In [2]:
k = 3 + 4
print(k)

7


In [3]:
(k+1)*(k-1)

48

In [4]:
(x+1)*(x-1)

NameError: name 'x' is not defined

In [ ]:
h=(k+2)*3+\
3+(k+7)
print(h)

Упражение 3

In [6]:
%whos

Variable   Type    Data/Info
----------------------------
a          int     -1
b          int     3
c          int     2
k          int     7


$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$

In [7]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])?  н
Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


In [8]:
x, y, z, t = 1, 2, 3, 4

In [9]:
%whos

Variable   Type    Data/Info
----------------------------
t          int     4
x          int     1
y          int     2
z          int     3


$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$

In [10]:
del(x)

In [21]:
%whos

Variable   Type       Data/Info
-------------------------------
A          ndarray    4: 4 elems, type `int64`, 32 bytes
B          ndarray    2x6: 12 elems, type `int64`, 96 bytes
R          ndarray    4x3: 12 elems, type `int64`, 96 bytes
S          ndarray    3: 3 elems, type `float64`, 24 bytes
np         module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
t          int        4
v          ndarray    4: 4 elems, type `int64`, 32 bytes
y          int        2
z          int        3


In [2]:
import numpy as np

B = np.array([1, 3, -1])
print(B)

[ 1  3 -1]


In [14]:
A = np.array( [ [1, 2, 3, 4], [0, 1, 3, 2] ] )
print(A)

[[1 2 3 4]
 [0 1 3 2]]


In [15]:
v = np.arange(1,8,2)
print (v)

[1 3 5 7]


In [18]:
A = np.arange(4)
print('A =', A)

B = np.arange(12).reshape(2, 6)
print('B =', B)

A = [0 1 2 3]
B = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [19]:
S = np.array([-1, np.sqrt(2), np.abs(-3)])
print (S)

[-1.          1.41421356  3.        ]


Упражнение 4

In [9]:
R = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9],
             [10, 11, 12]])

$\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \\ 10 & 11 & 12 \end{bmatrix}$

In [10]:
print(R)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
R[1][2] = - R[1][2]
print(R)

[[ 1  2  3]
 [ 4  5 -6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
R[0][2] -= 4
print(R)

[[ 1  2 -1]
 [ 4  5 -6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
R[:,1] *= 2
print(R)

[[  2   4  -2]
 [  8  10 -12]
 [ 14  16  18]
 [ 20  22  24]]


In [15]:
R[0,:] *= 2

In [16]:
print(R)

[[  4   8  -4]
 [  8  10 -12]
 [ 14  16  18]
 [ 20  22  24]]


In [19]:
a = np.array([1, 2, 3, 4, 5])
print(a)

b = np.array([1, 2, 3, 4, 5, 6, 7])
print(b)

c = np.array([1, 2])
d = np.array([1, 2, 3, 4])
e = np.array([1, 2, 3])
print(c, d, e)

[1 2 3 4 5]
[1 2 3 4 5 6 7]
[1 2] [1 2 3 4] [1 2 3]


In [38]:
from numpy import matlib

A = matlib.matrix('1, 2, 3; 4, 5, 6')
B = matlib.matrix('1, -2, 1; -2, 3, 4')
c = matlib.matrix('2')
D = matlib.ones((2, 3))
E = matlib.eye(3, 3)

In [23]:
print(A+B)

[[ 2  0  4]
 [ 2  8 10]]


In [24]:
print(A+c)

[[3 4 5]
 [6 7 8]]


In [25]:
print(A+E)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [26]:
print(A-B)

[[0 4 2]
 [6 2 2]]


In [27]:
print(A-c)

[[-1  0  1]
 [ 2  3  4]]


In [28]:
print(c*A)

ValueError: shapes (1,1) and (2,3) not aligned: 1 (dim 1) != 2 (dim 0)

In [30]:
print(np.matmul(A,B))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [31]:
print(np.matmul(A,np.transpose(B)))

[[ 0 16]
 [ 0 31]]


In [32]:
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Returns an array with axes transposed.
    
    For a 1-D array, this returns an unchanged view of the original array, as a
    transposed vector is simply the same vector.
    To convert a 1-D array into a 2-D column vector, an additional dimension
    must be added, e.g., ``np.atleast2d(a).T`` achieves this, as does
    ``a[:, np.newaxis]``.
    For a 2-D array, this is the standard matrix transpose.
    For an n-D array, if axes are given, their order indicates how the
    axes are permuted (see Examples). If axes are not provided, then
    ``transpose(a).shape == a.shape[::-1]``.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : tuple or list of ints, optional
        If specified, it must be a tuple or list which contains a permutation
        of [0,1,...,N-1] where N is the number of axes of `a`. The `i`'th axis
        of the returned array will correspond to the axis num

In [39]:
vec = np.array([1, 3, 5])
print(np.sqrt(vec))

[1.         1.73205081 2.23606798]


Упраженение С1

In [41]:
vec1 = np.arange(-2, 10, 2)
print(vec1*3)

[-6  0  6 12 18 24]


In [48]:
vec2 = np.arange(45, 5, -5)
print(np.shape(vec2))

(8,)


Упражнение С2

In [5]:
vec3 = np.arange(0, np.pi * 2, np.pi/6)
print('косинус: ', np.cos(vec3))
print()
print('синус: ', np.sin(vec3))
print()
print('тангенс: ', np.tan(vec3))

косинус:  [ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00 -8.66025404e-01
 -5.00000000e-01 -1.83697020e-16  5.00000000e-01  8.66025404e-01]

синус:  [ 0.00000000e+00  5.00000000e-01  8.66025404e-01  1.00000000e+00
  8.66025404e-01  5.00000000e-01  1.22464680e-16 -5.00000000e-01
 -8.66025404e-01 -1.00000000e+00 -8.66025404e-01 -5.00000000e-01]

тангенс:  [ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16  5.77350269e-01
  1.73205081e+00  5.44374645e+15 -1.73205081e+00 -5.77350269e-01]


In [7]:
vec4 = np.arange(-2, 2, 0.5)
print((np.cosh(vec4))**2 + (np.sinh(vec4))**2)

[27.30823284 10.067662    3.76219569  1.54308063  1.          1.54308063
  3.76219569 10.067662  ]
